const mongoose = require('mongoose');
const bcrypt = require('bcrypt');
const propertySchema = new mongoose.Schema(
  {
    propertyName: {
      type: String,
      required: true,
      trim: true,
    },
    address: {},
    landlord: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      ref: 'Landlord',
    },
    propertyName: {},
    propertyNum: {},
    address: {},
    isMortgaged: {},
    propertyOwnership: {},
    id: {},
    ownershipName: {},
    permissionToRent: {},
    isInsured: {},
    ownershipType: {},
    leaseholdCompany: {},
    leaseholdName: {},
    leaseholdNumber: {},
    leaseholdEmail: {},
    propertyType: {},
    maisonetteFloor: {},
    flatFloor: {},
    hasLift: {},
    councilTaxAuth: {},
    councilTaxNum: {},
    councilTaxBand: {},
    hasAlarm: {},
    alarmLocation: {},
    alarmCode: {},
    alarmCompany: {},
    alarmCompanyName: {},
    alarmCompanyNum: {},
    alarmCompanyRef: {},
    hasFireAlarm: {},
    fireAlarmLocation: {},
    fireAlarmCode: {},
    fireAlarmCompany: {},
    fireAlarmCompanyName: {},
    fireAlarmCompanyNum: {},
    fireAlarmCompanyRef: {},
    hasEmergencyLight: {},
    emergencyLightCompany: {},
    emergencyLightCompanyName: {},
    emergencyLightCompanyNum: {},
    waterCompany: {},
    waterMeter: {},
    waterMeterSerial: {},
    waterMeterLocation: {},
    waterMeterStopcock: {},
    stopcockOther: {},
    waterRefNum: {},
    elecCompany: {},
    elecMeter: {},
    elecMeterSerial: {},
    elecMeterLocation: {},
    elecFusebox: {},
    fuseboxOther: {},
    elecRefNum: {},
    gasCompany: {},
    gasMeter: {},
    gasMeterSerial: {},
    gasMeterLocation: {},
    gasShutoff: {},
    shutoffOther: {},
    gasRefNum: {},
    landline: {},
    landlineNum: {},
    broadband: {},
    broadbandCompany: {},
    broadbandPassword: {},
    broadbandLocation: {},
    refuseDay: {},
    refuseFreq: {},
    recycle: {},
    recycleDay: {},
    recycleFreq: {},
    bins: {},
    hasBoundaries: {},
    boundaries: {},
    boundariesOther: {},
    hasOutbuildings: {},
    outbuildings: {},
    outbuildingsOther: {},
  },
  { timestamps: true }
);

const Property = mongoose.model('Property', propertySchema);

module.exports = Property;
